package com.selfdualbrain.gui;

import javax.swing.*;
import java.awt.*;

public class ScopeItemPanel {
    private JCheckBox a01CheckBox;
    private JPanel panel1;
    private JRadioButton radioButton1;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        a01CheckBox = new JCheckBox();
        a01CheckBox.setSelected(true);
        a01CheckBox.setText("01");
        panel1.add(a01CheckBox, BorderLayout.WEST);
        radioButton1 = new JRadioButton();
        radioButton1.setText("");
        panel1.add(radioButton1, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
