package com.selfdualbrain.gui;

import javax.swing.*;
import java.awt.*;

public class XXXFilterEditor {
    private JCheckBox a01CheckBox;
    private JCheckBox a02CheckBox;
    private JCheckBox a03CheckBox;
    private JRadioButton a01RadioButton;
    private JRadioButton a02RadioButton;
    private JRadioButton a03RadioButton;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        a01CheckBox = new JCheckBox();
        a01CheckBox.setText("");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(a01CheckBox, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel1.add(spacer1, gbc);
        a02CheckBox = new JCheckBox();
        a02CheckBox.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(a02CheckBox, gbc);
        a03CheckBox = new JCheckBox();
        a03CheckBox.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(a03CheckBox, gbc);
        a01RadioButton = new JRadioButton();
        a01RadioButton.setText("01");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(a01RadioButton, gbc);
        a02RadioButton = new JRadioButton();
        a02RadioButton.setText("02");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(a02RadioButton, gbc);
        a03RadioButton = new JRadioButton();
        a03RadioButton.setText("03");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(a03RadioButton, gbc);
    }
}
